#=======================================================================
#@V@:Note: File automatically generated by VIDE makefile maker (14:38:49 08 Dec 1999) (g++).
#  This file regenerated each time you run VIDE, so save under a
#    new name if you hand edit, or it will be overwritten.
#=======================================================================

# Standard defines:
CC     	=	g++

HOMEV	=	
VPATH	=	$(HOMEV)/include
oDir	=	.
Bin	=	.
Src	=	.
libDirs	=
incDirs	=
LIBS	=	-lpython15 -lcomctl32 -mwindows
C_FLAGS	=	-O

SRCS	=\
	$(Src)/AtlasCodec.cpp\
	$(Src)/AtlasPackedAsciiProtocol.cpp\
	$(Src)/AtlasProtocolDecoder.cpp\
	$(Src)/AtlasProtocolEncoder.cpp\
	$(Src)/AtlasPackedAsciiDecoder.cpp\
	$(Src)/AtlasPackedAsciiEncoder.cpp\
	$(Src)/CodecBench.cpp\
	$(Src)/AtlasObject.cpp\
	$(Src)/AtlasProtocol.cpp

EXOBJS	=\
	$(oDir)/AtlasCodec.o\
	$(oDir)/AtlasPackedAsciiProtocol.o\
	$(oDir)/AtlasProtocolDecoder.o\
	$(oDir)/AtlasProtocolEncoder.o\
	$(oDir)/AtlasPackedAsciiDecoder.o\
	$(oDir)/AtlasPackedAsciiEncoder.o\
	$(oDir)/CodecBench.o\
	$(oDir)/AtlasObject.o\
	$(oDir)/AtlasProtocol.o

# User defines:

#@# Targets follow ---------------------------------

all:	$(Bin)/CodecBench

objs:	$(EXOBJS)

cleanobjs:
	rm -f $(EXOBJS)

cleanbin:
	rm -f $(Bin)/CodecBench

clean:	 cleanobjs

cleanall:	 cleanobjs cleanbin

#@# User Targets follow ---------------------------------


#@# Dependency rules follow -----------------------------

$(Bin)/CodecBench: $(EXOBJS)
	$(CC) -o $(Bin)/CodecBench $(EXOBJS) $(incDirs) $(libDirs) $(LIBS)

$(oDir)/AtlasCodec.o: AtlasCodec.cpp AtlasCodec.h AtlasObject.h \
 AtlasProtocol.h AtlasProtocolEncoder.h AtlasProtocolDecoder.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/AtlasPackedAsciiProtocol.o: AtlasPackedAsciiProtocol.cpp \
 AtlasProtocol.h AtlasProtocolEncoder.h AtlasObject.h \
 AtlasProtocolDecoder.h AtlasPackedAsciiProtocol.h \
 AtlasPackedAsciiEncoder.h AtlasPackedAsciiDecoder.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/AtlasProtocolDecoder.o: AtlasProtocolDecoder.cpp \
 AtlasProtocolDecoder.h AtlasObject.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/AtlasProtocolEncoder.o: AtlasProtocolEncoder.cpp \
 AtlasProtocolEncoder.h AtlasObject.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/AtlasPackedAsciiDecoder.o: AtlasPackedAsciiDecoder.cpp AtlasObject.h \
 AtlasProtocol.h AtlasProtocolEncoder.h AtlasProtocolDecoder.h \
 AtlasPackedAsciiDecoder.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/AtlasPackedAsciiEncoder.o: AtlasPackedAsciiEncoder.cpp \
 AtlasPackedAsciiEncoder.h AtlasObject.h AtlasProtocolEncoder.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/CodecBench.o: CodecBench.cpp AtlasCodec.h AtlasObject.h \
 AtlasProtocol.h AtlasProtocolEncoder.h AtlasProtocolDecoder.h \
 AtlasPackedAsciiProtocol.h AtlasPackedAsciiEncoder.h \
 AtlasPackedAsciiDecoder.h CodecBench.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/AtlasObject.o: AtlasObject.cpp AtlasObject.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<

$(oDir)/AtlasProtocol.o: AtlasProtocol.cpp AtlasProtocol.h \
 AtlasProtocolEncoder.h AtlasObject.h AtlasProtocolDecoder.h
	$(CC) $(C_FLAGS) $(incDirs) -c -o $@ $<
